version: '2'
services:
    masterdetail-app:
        image: masterdetail
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://masterdetail-mariadb:3306/masterdetail
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    masterdetail-mariadb:
        extends:
            file: mariadb.yml
            service: masterdetail-mariadb
